# netlify.toml
[build]
  command = "hugo mod get -u && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "Asia/Jakarta" 

[context.production.environment]
  HUGO_VERSION = "0.111.2"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.111.2"

[[redirects]]
  from = "https://jundimubarok.com"
  to = "https://jundi.web.id"
  status = 301
  force = true